=== juanmanuelcarrera/InfoArtist/basededatos.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT basededatos (artistas, canciones, albumes)>

<!ELEMENT artistas (artista+)>
<!ELEMENT artista (nombre_artistico, biografia, descripcionartista)>
<!ELEMENT nombre_artistico (#PCDATA)>
<!ELEMENT biografia (#PCDATA)>
<!ELEMENT descripcionartista (#PCDATA)>
<!ATTLIST artista id ID #REQUIRED>

<!ELEMENT canciones (cancion+)>
<!ELEMENT cancion (titulocancion, duracion, artistasid, albumesid)>
<!ELEMENT titulocancion (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT artistasid (artistaid+)>
<!ELEMENT albumesid (albumid+)>
<!ELEMENT artistaid EMPTY>
<!ELEMENT albumid EMPTY>
<!ATTLIST artistaid id IDREF #REQUIRED>
<!ATTLIST albumid id IDREF #REQUIRED>
<!ATTLIST cancion id ID #REQUIRED>

<!ELEMENT albumes (album+)>
<!ELEMENT album (tituloalbum, descripcionalbum, anio_publicacion, sello_discografico, url_imagen, artistasid)>
<!ELEMENT tituloalbum (#PCDATA)>
<!ELEMENT descripcionalbum (#PCDATA)>
<!ELEMENT anio_publicacion (#PCDATA)>
<!ELEMENT sello_discografico (#PCDATA)>
<!ELEMENT url_imagen (#PCDATA)>
<!ATTLIST album id ID #REQUIRED>

=== juanmanuelcarrera/InfoArtist/basededatos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE basededatos SYSTEM "basededatos.dtd">
<basededatos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="basededatos.xsd">
    <artistas>
        <artista id="a01">
            <nombre_artistico>Akon</nombre_artistico>
            <biografia>Hijo del percusionista Mor Thiam, Akon creció en una familia dedicada a la música y aprendió a tocar varios instrumentos, entre ellos el yembe. Nació en San Luis, Misuri, por lo que no tuvo ningún problema de inmigración, pero vivió en Dakar, Senegal, hasta los siete años de edad. Cabe destacar que su familia era musulmana, aunque él no siguió la religión musulmana. Durante un tiempo estuvo entre Estados Unidos y Senegal, Akon se asentó definitivamente en el país norteamericano a los 15 años de edad, cuando fijó su residencia en Jersey City, Nueva Jersey.
			También conoció la criminalidad de las calles y llegó en un par de ocasiones a la cárcel. Akon utilizó ese tiempo para canalizar sus conocimientos e intuiciones musicales. A su salida, realizó unas maquetas que, gracias a las gestiones de su mánager Devyne Stephens, encontraron un paso a los despachos de Universal. Así fue cómo se gestó su debut, ‘Trouble’, aparecido en 2004. En él se encontraba el éxito ‘Locked Up’, directamente inspirado en el tiempo que pasó entre rejas, así como ‘Guetto’, ‘Bananza’ o ‘Lonely’, canciones todas en las que se fraguaba el estilo peculiar de Akon que fusiona rap de las calles con elegantes melodías de soul, producción para el club y ritmos africanos. El disco fue multi-platino, y llegó a vender más de 3 millones de copias en el mundo.
			‘Guetto’ fue remezclada posteriormente para la radio, incluyendo reconocidísimos versos de los rappers 2Pac, The Notorious B.I.G. y artistas marroquíes afincados en Holanda como Yesser Rochdi, conocido artísticamente como YES-R y Ali B. Y, gracias a la popularidad ganada, hizo una aparición estelar en ‘Soul Survivor’, con Young Jeezy. Otras colaboraciones han tenido de co-protagonistas a R. Kelly, Obie Trice, Elton John, Daddy Yankee y Gwen Stefani, con la que ha compuesto un tema en su más reciente disco, ‘The Sweet Escape’ (Interscope, 2006). Además, se ha dado tiempo para crear su propio sello (Konvict Muzik), en donde publica a T-Pain y Rozonda “Chilli” Thomas.
			</biografia>
            <descripcionartista>Aliaune Damala Badara Thiam, más conocido como Akon (San Luis, Misuri, 16 de abril de 1973) es un cantante estadounidense-senegalés de hip hop, Pop y RandB, compositor, rapero, actor y productor musical. Saltó a la fama en 2004 con el single Locked Up de su primer álbum Trouble. En su segundo disco, Konvicted, se incluía el single Smack That, por el que fue nominado a los Grammy. Es el fundador de Konvict Muzik y Kon Live Distribution. Akon es conocido por cantar coros y ha colaborado en más de 175 canciones, 40 de ellas incluidos en el Billboard Hot 100. Cantó en la canción benéfica We Are The World 25 For Haití.  
			</descripcionartista>
        </artista>
        <artista id="a02">
            <nombre_artistico>Lil Wayne</nombre_artistico>
            <biografia>Dwayne Michael Carter, Jr. (nacido el 27 de septiembre 1982 en la ciudad de Nueva Orleans, Estados Unidos), mejor conocido por su nombre artístico Lil Wayne, es un rapero estadounidense ganador de cuatro Grammys. A la edad de nueve años, Lil Wayne fue contratado por el sello discográfico Cash Money Records como el miembro más joven del mismo, para formar parte del dúo, The BG'z, junto con B.G. . En 1997, Lil Wayne se unió al grupo Hot Boys, que incluía a los raperos Juvenile, BG, y Young Turk. Hot Boys debutó con Get It How U Live! ese mismo año. Lil Wayne obtuvo la mayor parte de su éxito con el álbum de mayores ventas del grupo: Guerrilla Warfare lanzado en 1999. También en 1999, Lil Wayne lanzó su primer disco de platino Tha Block Is Hot, vendiendo más de un millón de copias en los EE.UU. Y también cantó con la famosa TINGUI Sánchez en los Grammys Lil Wayne alcanzó la mayor popularidad en 2004 con The Carter, que incluía el single Go D.J. Wayne también apareció en el sencillo de las Destiny's Child Soldier de ese año. En 2005, se publicóTha Carter II, la secuela de Tha Carter. Su álbum más exitoso, Tha Carter III, fue lanzado en 2008 y vendió más de un millón de copias en los EE.UU. la primera semana de lanzamiento. Incluye su sencillo número uno Lollipop, con Static Major. También incluye los singles A Milli y Got Money con T-Pain y ganó el premio Grammypor Mejor Álbum de Rap. Lil Wayne lanzó su álbum debut de rock, Rebirth, en 2010- Aunque el recibimiento de la crítica no fue positivo, el álbum fue disco de oro. En marzo de 2010, Lil Wayne entró en prisión para cumplir una pena de cárcel de ocho meses en Nueva York tras ser declarado culpable de posesión ilícita de un arma derivada de un incidente ocurrido en julio de 2007. Durante su estancia en prisión, lanzó un nuevo álbum titulado I Am Not A Human Being en septiembre de 2010, con artistas de Young Money, tales como Drake, Nicki Minaj, Lil Twist y Tyga. Fue puesto en libertad el 29 de agosto de 2011. Su noveno álbum de estudio y el primero desde que fue liberado de prisión es Tha Carter IV. El álbum incluye canciones como 6 Foot 7 Foot, con Cory Gunz, How To Love y She Will, conDrake. Se vendieron 964.000 copias en los EE.UU. en su primera semana, batió el record de ventas digitales en iTunes Store y es certificado triple platino por sus ventas internacionales.
			</biografia>
            <descripcionartista>Dwayne Michael Carter, Jr. nació en el barrio de Hollygrove en Nueva Orleans, Estados Unidos, el 27 de septiembre de 1982. Su madre tenía diecinueve años cuando dio a luz y sus padres se divorciaron cuando él contaba dos años de edad. Su padre los abandonó finalmente a los 5 años, razón está la de no tener padre, que esgrime el rapero para haberse cambiado el nombre de pila al quitar la D inicial de Dwayne.
			Escribió su primera canción de rap a los ocho años. En 1991 conoció al rapero Bryan Williams(Birdman), dueño de la discográfica Cash Money Records, con la cual editarían su primer disco en colaboración, True Story con el rapero B. G., el proyecto se llamaría The B.G.'z, Carter contaba solo con once años. A los trece años, se disparó accidentalmente con una pistola y un policía tuvo que llevarlo de urgencia al hospital. A pesar de ser un brillante alumno, inscrito además en un club de teatro, dejó la escuela para dedicarse de lleno a su carrera musical.
			Lil Wayne es estadounidense. Wayne tiene una hija llamada Reginae nacida en 1998 con su exmujer Antonia Toya Carter.
			En octubre de 2008, nació su primer hijo varón Dwayne Michael Carter III, el cual tuvo con una mujer llamada Sarah Vivan.
			Un año después, en 2009, tuvo su tercer y cuarto hijo, uno con la actriz Lauren London y otro con la cantante Nivea. Los hijos se llaman Cameron Carter London y Neal Carter Nash, respectivamente. En una entrevista en CBS con Katie Couric, Wayne describe por qué se le conoce con el nombre de Wayne en lugar de su nombre de pila, Dwayne. Carter explicó, se me cayó la D porque ese es el nombre de mi padre y él no está ni nunca ha estado en mi vida. Así que no quiero ser Dwayne, prefiero ser Wayne. Couric le preguntó si su padre sabía esto y Wayne respondió lo sabe ahora, con una sonrisa irónica.
			Wayne le disparó a su padrastro cuando estaba golpeando a su madre, tras este hecho Wayne pasó tiempo en un correccional de menores.
			Lil Wayne se enteró a la edad de once años de que el que él creía que era su padre era su padrastro, esto fue un golpe muy duro para él.
			Lil Wayne tiene un hermano menor llamado Semaj Davis, hijo de su madre llamada Jocita Carter. Actualmente ha contraído nupcias con Valeria Segura una chica cristiana de origen Mexicano.
			Lil Wayne es un cristiano practicante que toma tiempo para leer la biblia con regularidad. Mientras se reproduce en Newark Symphony Hall, Lil Wayne afirma su creencia en Dios y Su Hijo, Jesús. De acuerdo con su ID interno Rikers Island y registros de la cárcel, Wayne es específicamente cristiano.
			</descripcionartista>
        </artista>
        <artista id="a03">
            <nombre_artistico>Eminem</nombre_artistico>
            <biografia>Nació en St. Joseph, Misuri, siendo el hijo de Marshall Bruce Mathers II y Debbie Nelson. Es de ancestros escoceses,  ingleses y, más lejanos, suizos y alemanes. Poco después de su nacimiento, su padre abandonó a su familia. Hasta los doce años Mathers y su madre se trasladaron en varias ciudades y pueblos de Misuri incluyendo St. Joseph, Savannah y Kansas City antes de ir a Warren, Míchigan, un suburbio de Detroit. Después de adquirir una copia del álbum de Beastie Boys, al ser un preadolescente, Mathers se interesó mucho en el hip hop. Interpretó de forma aficionada rap a los catorce años bajo el seudónimo de MandM, entrando en un grupo llamado Bassmint Productions y lanzando su primer EP llamado Steppin' Onto The Scene. Más tarde cambiaron su nombre a Soul Intent y alrededor de 1995 lanzaron su primer sencillo llamado Fuckin' Backstabber bajo el sello discográfico Mashin' Duck Records. A pesar de que fue inscrito en la escuela Lincoln High School en Warren frecuentemente participó en las batalla de freestyle en la escuela Osborn High School en la ciudad obteniendo la aprobación del público de underground hip hop.  Después de repetir el noveno grado tres veces debido a ausencias injustificadas abandonó la escuela a la edad de 17 años.
